#ifndef HARDWARE_INCLUDES_H
#define HARDWARE_INCLUDES_H

#define DRIVE_JAG_LEFT_FRONT 1
#define DRIVE_JAG_LEFT_REAR 2
#define DRIVE_JAG_RIGHT_FRONT 3
#define DRIVE_JAG_RIGHT_REAR 4


#define SOLENOID_PORT_ONE 1
#define SOLENOID_PORT_TWO 2

#endif
